#!/bin/bash

src_dir="."
out_dir="../docs"

find "$src_dir" -type f -name "*.md" | while read -r md; do
  # ./subdir/file.md → subdir/file.md
  rel="${md#./}"

  # subdir/file.md → subdir/file.html
  html="${rel%.md}.html"

  # 出力先: ../docs/subdir/file.html
  out="${out_dir}/${html}"

  # 出力先ディレクトリを作成
  mkdir -p "$(dirname "$out")"

  # HTML化
  pandoc "$md" -s -c style.css -o "$out"
done
